FROM python:3.9-slim

# 1. Встановлюємо Chrome і необхідні системні бібліотеки
RUN apt-get update && apt-get install -y wget gnupg2 unzip curl

# Додаємо ключі Google Chrome
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'

# Встановлюємо стабільну версію Chrome
RUN apt-get update && apt-get install -y google-chrome-stable

# 2. Копіюємо файли бота
WORKDIR /app
COPY . /app

# 3. Встановлюємо Python-бібліотеки
RUN pip install --no-cache-dir -r requirements.txt

# 4. Запускаємо бота
CMD ["python", "main.py"]